name: Selenium Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Install Selenium
      run: |
        pip install selenium

    - name: Run Selenium Test
      run: |
        docker run --name api_test -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject \
        -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/infra:/usr/src/tests/AirbnbSeleniumGridProject/infra \
        -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/logic:/usr/src/tests/AirbnbSeleniumGridProject/logic \
        -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/test:/usr/src/tests/AirbnbSeleniumGridProject/test \
        python:latest python /usr/src/tests/AirbnbSeleniumGridProject/test/world_page_test.py
