name: Selenium Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Setup ChromeDriver
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: latest

    - name: Print current directory path
      run: echo Current directory path $(pwd)

    - name: Run Selenium Test
      run: |
        docker run --name api_test -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject -v ${{ github.workspace }}/infra:/usr/src/tests/AirbnbSeleniumGridProject/infra -v ${{ github.workspace }}/logic:/usr/src/tests/AirbnbSeleniumGridProject/logic tests:latest python test/world_page_test.py
