name: Selenium Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d '.' -f 1)
          CHROME_DRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION})
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/${CHROME_DRIVER_VERSION}/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Selenium
        run: |
          pip install selenium

      - name: Run Selenium Test
        run: |
          docker run --name api_test -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject \
          -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/infra:/usr/src/tests/AirbnbSeleniumGridProject/infra \
          -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/logic:/usr/src/tests/AirbnbSeleniumGridProject/logic \
          -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/test:/usr/src/tests/AirbnbSeleniumGridProject/test \
          your_custom_docker_image python /usr/src/tests/AirbnbSeleniumGridProject/test/world_page_test.py
