name: Selenium Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        run: |
          CHROME_DRIVER_VERSION="92.0.4515.107"
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp
          docker build -t tests:latest .

        shell: bash

      - name: Install Selenium
        run: |
          pip install selenium

      - name: Run Selenium Test
        run: |
          docker run --name api_test -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject \
          -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/infra:/usr/src/tests/AirbnbSeleniumGridProject/infra \
          -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/logic:/usr/src/tests/AirbnbSeleniumGridProject/logic \
          -v /home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/test:/usr/src/tests/AirbnbSeleniumGridProject/test \
          tests python /usr/src/tests/AirbnbSeleniumGridProject/test/world_page_test.py
