name: Selenium Test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      INFRA_PATH: '/home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/infra'
      LOGIC_PATH: '/home/runner/work/AirbnbSeleniumGridProject/AirbnbSeleniumGridProject/logic'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          node-version: '20'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup ChromeDriver
        run: |
          CHROME_DRIVER_VERSION="92.0.4515.107"
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp
          docker build -t tests:latest .

      - name: Install Selenium
        run: |
          pip install selenium

      - name: Run Selenium Tests
        run: |
          docker run --name api_test_chrome -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject -v $INFRA_PATH:/usr/src/tests/AirbnbSeleniumGridProject/infra -v $LOGIC_PATH:/usr/src/tests/AirbnbSeleniumGridProject/logic tests python C:\Users\odehm\Desktop\new\AirbnbSeleniumGridProject\test\world_page_test.py

          docker run --name api_test_edge -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject -v $INFRA_PATH:/usr/src/tests/AirbnbSeleniumGridProject/infra -v $LOGIC_PATH:/usr/src/tests/AirbnbSeleniumGridProject/logic tests python /usr/src/tests/AirbnbSeleniumGridProject/test/world_page_test.py

          docker run --name api_test_firefox -e PYTHONPATH=/usr/src/tests/AirbnbSeleniumGridProject -v $INFRA_PATH:/usr/src/tests/AirbnbSeleniumGridProject/infra -v $LOGIC_PATH:/usr/src/tests/AirbnbSeleniumGridProject/logic tests python /usr/src/tests/AirbnbSeleniumGridProject/test/world_page_test.py
